export const ADD_BAG = 'ADD_BAG';
export const UPDATE_BAG = 'UPDATE_BAG';
export const DELETE_BAG = 'DELETE_BAG';
export const LOAD_BAGS = 'LOAD_BAGS';

export const ADD_DISPLAY_OPTION = 'ADD_DISPLAY_OPTION';
export const UPDATE_HAND = 'UPDATE_HAND';
export const UPDATE_GRID_COLOR = 'UPDATE_GRID_COLOR';
export const UPDATE_GRIDLINE_COLOR = 'UPDATE_GRIDLINE_COLOR';
export const LOAD_DISPLAY_OPTIONS = 'LOAD_DISPLAY_OPTIONS';

export const OPEN_COLOR_PICKER = 'OPEN_COLOR_PICKER';
export const CLOSE_COLOR_PICKER = 'CLOSE_COLOR_PICKER';
export const CHANGE_COLOR = 'CHANGE_COLOR';

