export const ADD_BAG = 'ADD_BAG';
export const UPDATE_BAG = 'UPDATE_BAG';
export const DELETE_BAG = 'DELETE_BAG';
export const LOAD_BAGS = 'LOAD_BAGS';

export const LOAD_BAGGED_DISCS = 'LOAD_BAGGED_DISCS';
export const ADD_DISC = 'ADD_DISC';
export const FETCH_DISCS_BEGIN = 'FETCH_DISCS_BEGIN';
export const FETCH_DISCS_SUCCESS = 'FETCH_DISCS_SUCCESS';
export const FETCH_DISCS_FAILURE = 'FETCH_DISCS_FAILURE';
export const UPDATE_DISC_ENABLED = 'UPDATE_DISC_ENABLED';
export const UPDATE_DISC_COLOR = 'UPDATE_DISC_COLOR';
export const DELETE_DISC = 'DELETE_DISC';

export const ADD_DISPLAY_OPTION = 'ADD_DISPLAY_OPTION';
export const UPDATE_HAND = 'UPDATE_HAND';
export const UPDATE_GRID_COLOR = 'UPDATE_GRID_COLOR';
export const UPDATE_GRIDLINE_COLOR = 'UPDATE_GRIDLINE_COLOR';
export const LOAD_DISPLAY_OPTIONS = 'LOAD_DISPLAY_OPTIONS';

export const TOGGLE_BAG_MODAL = 'TOGGLE_BAG_MODAL';
export const BAG_NAME_ON_CHANGE = 'BAG_NAME_ON_CHANGE';

export const OPEN_COLOR_PICKER = 'OPEN_COLOR_PICKER';
export const CLOSE_COLOR_PICKER = 'CLOSE_COLOR_PICKER';
export const CHANGE_COLOR = 'CHANGE_COLOR';

